development:
  adapter: postgresql
  encoding: unicode
  database: assess_w6
  pool: 5
  username: gschool
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: assess_w6_test
  pool: 5
  username: gschool
  password: